from __future__ import annotations

from datetime import UTC, datetime


def now_iso() -> str:
    return datetime.now(UTC).isoformat()


MISSIONS = [
    {
        "id": "mis-ai-opportunities",
        "name": "India AI Opportunity Radar",
        "prompt": "Track AI-related government opportunities in India with organisation, deadline, eligibility, value, location and official source.",
        "status": "active",
        "coverage": 89,
        "record_count": 42,
        "change_count": 7,
        "last_run": "11 minutes ago",
        "next_run": "in 5h 49m",
        "cadence": "Every 6 hours",
    },
    {
        "id": "mis-regulatory",
        "name": "Regulatory Change Watch",
        "prompt": "Track central rules, notifications and amendments affecting digital businesses in India.",
        "status": "active",
        "coverage": 94,
        "record_count": 128,
        "change_count": 12,
        "last_run": "38 minutes ago",
        "next_run": "in 2h 22m",
        "cadence": "Every 3 hours",
    },
    {
        "id": "mis-climate",
        "name": "Climate Procurement Lens",
        "prompt": "Find public procurement opportunities connected to climate technology and clean energy.",
        "status": "attention",
        "coverage": 71,
        "record_count": 67,
        "change_count": 3,
        "last_run": "2 hours ago",
        "next_run": "paused",
        "cadence": "Daily",
    },
]


SOURCES = [
    {
        "id": "src-india-code",
        "name": "India Code",
        "owner": "Ministry of Law and Justice / NIC",
        "type": "Official legislation",
        "url": "https://www.indiacode.nic.in/",
        "authority": 100,
        "freshness": "Live connector",
        "status": "healthy",
        "records": 534,
        "last_checked": "8 min ago",
    },
    {
        "id": "src-egazette",
        "name": "eGazette of India",
        "owner": "Department of Publication",
        "type": "Official gazette",
        "url": "https://egazette.nic.in/",
        "authority": 100,
        "freshness": "Monitored",
        "status": "healthy",
        "records": 286,
        "last_checked": "14 min ago",
    },
    {
        "id": "src-cppp",
        "name": "Central Public Procurement Portal",
        "owner": "Government of India",
        "type": "Official procurement",
        "url": "https://eprocure.gov.in/eprocure/app",
        "authority": 98,
        "freshness": "Monitored",
        "status": "healthy",
        "records": 119,
        "last_checked": "19 min ago",
    },
    {
        "id": "src-data-gov",
        "name": "Open Government Data Platform",
        "owner": "MeitY / NIC",
        "type": "Public data API",
        "url": "https://www.data.gov.in/",
        "authority": 96,
        "freshness": "API ready",
        "status": "healthy",
        "records": 78,
        "last_checked": "23 min ago",
    },
    {
        "id": "src-meity",
        "name": "MeitY",
        "owner": "Ministry of Electronics and IT",
        "type": "Ministry publications",
        "url": "https://www.meity.gov.in/",
        "authority": 97,
        "freshness": "Monitored",
        "status": "degraded",
        "records": 44,
        "last_checked": "1h ago",
    },
]


RECORDS = [
    {
        "id": "rec-001",
        "organisation": "IndiaAI / MeitY",
        "opportunity": "AI Compute and Services Empanelment",
        "deadline": "11 Oct 2026",
        "eligibility": "Cloud and AI infrastructure providers",
        "value": "Not disclosed",
        "location": "Pan India",
        "status": "Updated",
        "confidence": 97,
        "sources": 3,
        "changed": True,
    },
    {
        "id": "rec-002",
        "organisation": "Department of Science & Technology",
        "opportunity": "Responsible AI Research Challenge",
        "deadline": "28 Oct 2026",
        "eligibility": "Indian universities and research labs",
        "value": "INR 2.4 Cr",
        "location": "India",
        "status": "Open",
        "confidence": 94,
        "sources": 2,
        "changed": False,
    },
    {
        "id": "rec-003",
        "organisation": "Digital India Corporation",
        "opportunity": "Language AI Innovation Programme",
        "deadline": "05 Nov 2026",
        "eligibility": "Startups, MSMEs and academic consortia",
        "value": "INR 75 Lakh",
        "location": "New Delhi / Remote",
        "status": "Open",
        "confidence": 92,
        "sources": 4,
        "changed": False,
    },
    {
        "id": "rec-004",
        "organisation": "National Health Authority",
        "opportunity": "AI-assisted Claims Anomaly Detection",
        "deadline": "17 Oct 2026",
        "eligibility": "Indian technology companies",
        "value": "Under review",
        "location": "New Delhi",
        "status": "Conflict",
        "confidence": 68,
        "sources": 3,
        "changed": True,
    },
    {
        "id": "rec-005",
        "organisation": "Bureau of Indian Standards",
        "opportunity": "AI Assurance Standards Consultation",
        "deadline": "21 Nov 2026",
        "eligibility": "Industry, academia and civil society",
        "value": "Consultation",
        "location": "Pan India",
        "status": "New",
        "confidence": 99,
        "sources": 2,
        "changed": True,
    },
    {
        "id": "rec-006",
        "organisation": "NITI Aayog",
        "opportunity": "AI for District Transformation Cohort",
        "deadline": "30 Nov 2026",
        "eligibility": "GovTech startups with deployed pilots",
        "value": "INR 1.1 Cr",
        "location": "12 aspirational districts",
        "status": "Open",
        "confidence": 88,
        "sources": 2,
        "changed": False,
    },
]


CHANGES = [
    {
        "id": "chg-001",
        "record_id": "rec-001",
        "kind": "deadline_changed",
        "impact": "high",
        "title": "Application deadline extended",
        "entity": "AI Compute and Services Empanelment",
        "before": "03 Oct 2026",
        "after": "11 Oct 2026",
        "source": "IndiaAI official notice",
        "time": "21 minutes ago",
        "confidence": 97,
    },
    {
        "id": "chg-002",
        "record_id": "rec-005",
        "kind": "record_added",
        "impact": "medium",
        "title": "New consultation discovered",
        "entity": "AI Assurance Standards Consultation",
        "before": None,
        "after": "Published",
        "source": "BIS official publication",
        "time": "44 minutes ago",
        "confidence": 99,
    },
    {
        "id": "chg-003",
        "record_id": "rec-004",
        "kind": "conflict_opened",
        "impact": "high",
        "title": "Project value disagreement",
        "entity": "AI-assisted Claims Anomaly Detection",
        "before": "INR 3.2 Cr",
        "after": "INR 4.0 Cr",
        "source": "Tender corrigendum vs listing page",
        "time": "1 hour ago",
        "confidence": 68,
    },
]


REVIEWS = [
    {
        "id": "rev-001",
        "priority": "critical",
        "title": "Conflicting procurement value",
        "record": "AI-assisted Claims Anomaly Detection",
        "field": "value",
        "recommended": "INR 4.0 Cr",
        "reason": "A newer official corrigendum conflicts with the portal summary.",
        "confidence": 68,
        "sources": ["Official corrigendum", "CPPP listing", "Department summary"],
    },
    {
        "id": "rev-002",
        "priority": "high",
        "title": "Possible opportunity removal",
        "record": "Agriculture Vision AI Pilot",
        "field": "status",
        "recommended": "Await next refresh",
        "reason": "The source returned 404 once; deletion grace policy requires two confirmations.",
        "confidence": 54,
        "sources": ["Department tender page"],
    },
    {
        "id": "rev-003",
        "priority": "normal",
        "title": "Eligibility text materially changed",
        "record": "Language AI Innovation Programme",
        "field": "eligibility",
        "recommended": "Accept new official text",
        "reason": "The official PDF adds MSMEs as an eligible applicant class.",
        "confidence": 91,
        "sources": ["Official programme PDF", "DIC announcement"],
    },
]


EVIDENCE = {
    "rec-001": {
        "field": "deadline",
        "value": "11 Oct 2026",
        "confidence": 97,
        "components": {"authority": 100, "freshness": 100, "agreement": 91, "directness": 100, "extraction": 94},
        "resolution": "The latest dated official notice supersedes the earlier programme page. Two independent official references agree.",
        "observations": [
            {
                "relation": "supports",
                "source": "IndiaAI official notice",
                "url": "https://indiaai.gov.in/",
                "locator": "Corrigendum, page 1, deadline row",
                "excerpt": "The last date for submission has been extended to 11 October 2026.",
                "fetched": "26 Sep 2026, 20:58 IST",
                "authority": 100,
            },
            {
                "relation": "supports",
                "source": "MeitY programme update",
                "url": "https://www.meity.gov.in/",
                "locator": "Updates section, item 4",
                "excerpt": "Revised submission deadline: 11.10.2026",
                "fetched": "26 Sep 2026, 21:03 IST",
                "authority": 97,
            },
            {
                "relation": "supersedes",
                "source": "Original programme page",
                "url": "https://indiaai.gov.in/",
                "locator": "Key dates",
                "excerpt": "Applications close on 03 October 2026.",
                "fetched": "25 Sep 2026, 18:00 IST",
                "authority": 100,
            },
        ],
    },
    "rec-004": {
        "field": "value",
        "value": "INR 4.0 Cr",
        "confidence": 68,
        "components": {"authority": 100, "freshness": 96, "agreement": 42, "directness": 94, "extraction": 88},
        "resolution": "Recommended but held for review. The corrigendum is newer and more direct, while the official listing still shows INR 3.2 Cr.",
        "observations": [
            {
                "relation": "supports",
                "source": "Official tender corrigendum",
                "url": "https://eprocure.gov.in/eprocure/app",
                "locator": "Financial terms, page 3",
                "excerpt": "The estimated project value shall be read as INR 4,00,00,000.",
                "fetched": "26 Sep 2026, 19:47 IST",
                "authority": 100,
            },
            {
                "relation": "conflicts",
                "source": "CPPP listing page",
                "url": "https://eprocure.gov.in/eprocure/app",
                "locator": "Tender value field",
                "excerpt": "Tender Value: INR 3,20,00,000",
                "fetched": "26 Sep 2026, 19:45 IST",
                "authority": 98,
            },
        ],
    },
}


RUN_EVENTS = [
    {"time": "21:04:16", "type": "publish", "message": "Dataset v18 published", "detail": "42 records · 89% coverage"},
    {"time": "21:04:09", "type": "resolve", "message": "Canonical values reconciled", "detail": "126 field values · 1 escalated"},
    {"time": "21:03:41", "type": "extract", "message": "Official PDF parsed", "detail": "BIS consultation · 14 observations"},
    {"time": "21:02:58", "type": "change", "message": "Deadline change detected", "detail": "03 Oct → 11 Oct"},
    {"time": "21:02:11", "type": "fetch", "message": "Incremental source pass complete", "detail": "17 unchanged · 3 changed · 0 failed"},
]

